name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup volta
        uses: volta-cli/action@v1

      - name: Set NODE_VERSION env variable
        run: echo "NODE_VERSION=$(node -v)" >> $GITHUB_ENV

      - name: Cache npm cache & node_modules
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-${{ env.NODE_VERSION }}-

      - name: Install dependencies
        run: npm ci
        if: steps.cache-dependencies.outputs.cache-hit != 'true'

      - name: test
        run: npm run test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
